[build]
  command = "npm install && npm run build"  # Replace with your build command
  publish = "dist"  # Replace with the folder where your built files are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

